version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

build:
  os: ubuntu-20.04
  tools:
    python: "2.7"

python:
  install:
    - requirements: pip_require.txt
    - requirements: requirements.txt