name: "Post preview links for changed files"

on:
    pull_request: ~

jobs:
    post-preview-links:
        name: Post preview links for changed files
        uses: ibexa/documentation-developer/.github/workflows/preview_comment.yaml@master
        with:
            project: 'projects/userguide/'
